### ISSUE TITLE
Compilation failure on CentOS 6.5

### ISSUE THREAD

**Issue by MagpiePKU** [vincent-dk/epiG#1]
g++ -m64 -I/usr/include/R -DNDEBUG  -I/usr/local/include -I"/usr/lib64/R/library/Rcpp/include" -I"/usr/lib64/R/library/RcppProgress/include" -I"/usr/lib64/R/library/RcppArmadillo/include"  -Iinclude -fopenmp -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic  -c epiG.cpp -o epiG.o
In file included from rtools.h:25:0,
                 from epiG.cpp:43:
rtools/rObject_def.h: In constructor ‘rObject::rObject(const std::vector<std::basic_string<char> >&, bool)’:
rtools/rObject_def.h:247:49: error: ‘mkChar’ was not declared in this scope
       SET_STRING_ELT(exp, i, mkChar(v[i].c_str()));
                                                 ^
rtools/rObject_def.h: In constructor ‘rObject::rObject(const string&, bool)’:
rtools/rObject_def.h:262:45: error: ‘mkChar’ was not declared in this scope
      SET_STRING_ELT(exp, 0, mkChar(v.c_str()));
                                             ^

make: *** [epiG.o] Error 1

**Comment by vincent-dk** [comment]
This is a problem with the R installation. It looks like there is a problem with the R headers, mkChar is an internal R function and must be available. You could try reinstalling R.

**Comment by markheron** [comment]
I had the same issue on:
```
R version 3.2.5 (2016-04-14)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu precise (12.04.5 LTS)
```

using the Rf_mkChar function instead of (the renamed reference) mkChar appears to have solved the issue.

I'm not 100% sure of the underlying problem, but it could be that your compiler vincent-dk automatically adds the required includes (R.h and/or Rinternals.h) while g++ does not do that by default. Checking the Rcpp package they also use Rf_mkChar everywhere and not mkChar. (see [Rf_mkChar](https://github.com/RcppCore/Rcpp/search?utf8=%E2%9C%93&q=Rf_mkChar v) vs [mkChar](https://github.com/RcppCore/Rcpp/search?utf8=%E2%9C%93&q=mkChar&type=Code), which is only the C API example)

**Comment by vincent-dk** [comment]
I have changed mkChar to Rf_mkChar. 

Now when I think about it, I guess it is probably best to use the Rf function names, the other might name clash and have probably been deleted on some systems.
